collections:
  test_categories:
    output: true
    sort_by: name
  tests:
    output: true
    sort_by: added_on

defaults:
  - scope:
      path: ""
      type: "test_categories"
    values:
      layout: "test_category"
  - scope:
      path: ""
      type: "tests"
    values:
      layout: "test"
  - scope:
      path: ""
    values:
      layout: "default"

